name: Python

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
      - uses: actions/checkout@v3
      
      - name: 파이썬 버전 세팅 ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          
      - name: 파이썬 버전 출력
        run: python -c "import sys; print(sys.version)"
        
      - name: 아키팩트 생성 중..
        run: |
          echo ${{ matrix.python-version }} > version.txt
        id: version
        
      - name: 아키팩트 업로드
        uses: actions/upload-artifact@v2
        with:
          name: 파이썬 버
          path: version.txt
